# Generated by Django 4.2.7 on 2023-11-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('slug', models.SlugField(help_text='Используйте буквы, цифры или @/./+/-/_ ', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(default='Default group name', help_text='Введите название, длина до 100 символов', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение группы', null=True, upload_to='uploads/groups_images', verbose_name='Изображение группы')),
                ('group_members', models.ManyToManyField(related_name='users_groups', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_groups', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
