# Generated by Django 4.2.7 on 2023-11-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
        ('users_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_containers', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Контейнер сообщений группы',
                'verbose_name_plural': 'Контейнеры сообщений группы',
            },
        ),
        migrations.CreateModel(
            name='UserGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время отправки')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to='users_messages.dailygroupmessages', verbose_name='Контейнер')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение группы',
                'verbose_name_plural': 'Сообщения группы',
            },
        ),
    ]
